<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.adrug.erp</groupId>
        <artifactId>adrug-svc-bus</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <groupId>com.adrug.erp</groupId>
    <artifactId>adrug-svc-bus-pms</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>adrug-svc-bus-pms</name>
    <description>采购管理（采购订单、收货单、验收单、采购入库单）</description>
    <modules>
        <module>adrug-svc-bus-pms-interface</module>
        <module>adrug-svc-bus-pms-model</module>
        <module>adrug-svc-bus-pms-repository</module>
        <module>adrug-svc-bus-pms-provider</module>
    </modules>
</project>