<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.adrug.erp</groupId>
        <artifactId>adrug-app</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <groupId>com.adrug.erp</groupId>
    <artifactId>adrug-app-term</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>adrug-app-term</name>
    <description>终端接入（POS收银台、手机应用）</description>
    <modules>
        <module>adrug-app-term-service</module>
        <module>adrug-app-term-boot</module>
    </modules>
</project>
