-- 业务库：adrug-bus-pms（采购管理：采购订单、收货单、验收单、采购入库单）
-- 库级分租户：tenant_id % 2 → adrug_bus_pms_0 / adrug_bus_pms_1
-- 表字段保存真实租户 ID（tenant_id 作分片键）
CREATE DATABASE IF NOT EXISTS `adrug_bus_pms_0`
  DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS `adrug_bus_pms_1`
  DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- =====================================================================
-- adrug_bus_pms_0
-- =====================================================================
USE `adrug_bus_pms_0`;

-- 采购订单主表（业务实体，含定制化字段 cust1~cust6）
CREATE TABLE `purchase_order` (
    `id`             BIGINT        NOT NULL                COMMENT '主键（雪花ID）',
    `tenant_id`      BIGINT        NOT NULL                COMMENT '租户ID（真实值，分片键）',
    `org_id`         BIGINT        NOT NULL                COMMENT '机构ID（药店/门店）',
    `order_no`       VARCHAR(64)   NOT NULL                COMMENT '采购订单号',
    `supplier_id`    BIGINT        NOT NULL                COMMENT '供应商ID（关联供应商信息）',
    `supplier_name`  VARCHAR(128)  NULL                    COMMENT '供应商名称',
    `supplier_salesman`      VARCHAR(64)   NULL            COMMENT '供应商业务员',
    `order_date`     DATE          NULL                    COMMENT '下单日期',
    `handler`                 VARCHAR(64)   NULL           COMMENT '经手人',
    `purchaser`               VARCHAR(64)   NULL           COMMENT '采购员',
    `payment_method`          VARCHAR(32)   NULL           COMMENT '付款方式',
    `settlement_method`       VARCHAR(32)   NULL           COMMENT '结算方式',
    `pre_settlement_date`     DATE          NULL           COMMENT '预结算日期',
    `invoice_type`            VARCHAR(32)   NULL           COMMENT '发票类型',
    `delivery_method`         VARCHAR(32)   NULL           COMMENT '送货方式',
    `estimated_arrival_time`  DATETIME      NULL           COMMENT '预计到货时间',
    `status`         TINYINT       NOT NULL DEFAULT 0      COMMENT '单据状态：0-制单保存，1-制单完成（BillStatusEnum）',
    `total_qty`      DECIMAL(18,4) NOT NULL DEFAULT 0      COMMENT '采购数量合计',
    `total_amount`   DECIMAL(18,2) NOT NULL DEFAULT 0      COMMENT '采购金额合计',
    `post_time`      DATETIME      NULL                    COMMENT '过账时间',
    `cancel_reason`  VARCHAR(500)  NULL                    COMMENT '取消理由',
    `cancel_note`    VARCHAR(500)  NULL                    COMMENT '取消说明',
    `remark`         VARCHAR(500)  NULL                    COMMENT '备注',
    `create_time`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_user_id` BIGINT        NULL                    COMMENT '创建人（用户ID）',
    `update_user_id` BIGINT        NULL                    COMMENT '更新人（用户ID）',
    `deleted`        TINYINT       NOT NULL DEFAULT 0      COMMENT '逻辑删除标记：0-未删除，1-已删除',
    `version`        INT           NOT NULL DEFAULT 0      COMMENT '乐观锁版本号',
    `cust1`          VARCHAR(255)  NULL                    COMMENT '定制化字段1',
    `cust2`          VARCHAR(255)  NULL                    COMMENT '定制化字段2',
    `cust3`          VARCHAR(255)  NULL                    COMMENT '定制化字段3',
    `cust4`          VARCHAR(255)  NULL                    COMMENT '定制化字段4',
    `cust5`          VARCHAR(255)  NULL                    COMMENT '定制化字段5',
    `cust6`          VARCHAR(255)  NULL                    COMMENT '定制化字段6',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tenant_order_no` (`tenant_id`, `order_no`),
    KEY `idx_tenant_supplier` (`tenant_id`, `supplier_id`),
    KEY `idx_tenant_status` (`tenant_id`, `status`)
) ENGINE = InnoDB COMMENT = '采购订单主表';

-- 采购订单明细表
CREATE TABLE `purchase_order_item` (
    `id`             BIGINT        NOT NULL                COMMENT '主键（雪花ID）',
    `tenant_id`      BIGINT        NOT NULL                COMMENT '租户ID（真实值，分片键）',
    `org_id`         BIGINT        NOT NULL                COMMENT '机构ID（药店/门店）',
    `order_id`       BIGINT        NOT NULL                COMMENT '采购订单ID（关联 purchase_order.id）',
    `seq_no`         INT           NULL                    COMMENT '序号',
    `drug_id`        BIGINT        NULL                    COMMENT '商品ID（关联商品信息）',
    `drug_code`      VARCHAR(64)   NULL                    COMMENT '商品编码',
    `generic_name`   VARCHAR(128)  NULL                    COMMENT '通用药品名称',
    `drug_name`      VARCHAR(128)  NULL                    COMMENT '商品名称',
    `spec`           VARCHAR(64)   NULL                    COMMENT '规格',
    `unit`           VARCHAR(16)   NULL                    COMMENT '单位',
    `origin`         VARCHAR(128)  NULL                    COMMENT '产地',
    `manufacturer`   VARCHAR(128)  NULL                    COMMENT '生产厂家',
    `qty`            DECIMAL(18,4) NOT NULL DEFAULT 0      COMMENT '采购数量',
    `price`          DECIMAL(18,4) NOT NULL DEFAULT 0      COMMENT '采购单价',
    `amount`         DECIMAL(18,2) NOT NULL DEFAULT 0      COMMENT '采购金额',
    `received_qty`           DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '收货数量',
    `received_amount`        DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '收货金额',
    `received_reject_qty`    DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '收货拒收数量',
    `received_reject_amount` DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '收货拒收金额',
    `source_type`            VARCHAR(32)   NULL            COMMENT '源单据类型',
    `source_order_no`        VARCHAR(64)   NULL            COMMENT '源单号',
    `remark`         VARCHAR(500)  NULL                    COMMENT '备注',
    `create_time`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_user_id` BIGINT        NULL                    COMMENT '创建人（用户ID）',
    `update_user_id` BIGINT        NULL                    COMMENT '更新人（用户ID）',
    `deleted`        TINYINT       NOT NULL DEFAULT 0      COMMENT '逻辑删除标记：0-未删除，1-已删除',
    `version`        INT           NOT NULL DEFAULT 0      COMMENT '乐观锁版本号',
    `cust1`          VARCHAR(255)  NULL                    COMMENT '定制化字段1',
    `cust2`          VARCHAR(255)  NULL                    COMMENT '定制化字段2',
    `cust3`          VARCHAR(255)  NULL                    COMMENT '定制化字段3',
    `cust4`          VARCHAR(255)  NULL                    COMMENT '定制化字段4',
    `cust5`          VARCHAR(255)  NULL                    COMMENT '定制化字段5',
    `cust6`          VARCHAR(255)  NULL                    COMMENT '定制化字段6',
    PRIMARY KEY (`id`),
    KEY `idx_order_id` (`order_id`),
    KEY `idx_tenant_drug` (`tenant_id`, `drug_id`)
) ENGINE = InnoDB COMMENT = '采购订单明细表';

-- 收货单主表
CREATE TABLE `receiving_order` (
    `id`             BIGINT        NOT NULL                COMMENT '主键（雪花ID）',
    `tenant_id`      BIGINT        NOT NULL                COMMENT '租户ID（真实值，分片键）',
    `org_id`         BIGINT        NOT NULL                COMMENT '机构ID（药店/门店）',
    `order_no`       VARCHAR(64)   NOT NULL                COMMENT '收货单号',
    `source_type`    TINYINT       NOT NULL DEFAULT 1      COMMENT '数据来源：1-采购订单，2-退货（SourceTypeEnum）',
    `source_order_id` BIGINT       NULL                    COMMENT '来源单据ID（采购订单ID等）',
    `supplier_id`    BIGINT        NOT NULL                COMMENT '往来单位ID（供应商/退货单位）',
    `supplier_name`  VARCHAR(128)  NULL                    COMMENT '往来单位名称',
    `warehouse_id`   BIGINT        NOT NULL                COMMENT '收货仓库ID（关联仓库信息）',
    `warehouse_name` VARCHAR(128)  NULL                    COMMENT '收货仓库名称',
    `arrival_no`     VARCHAR(64)   NULL                    COMMENT '来货单号',
    `receive_date`   DATE          NULL                    COMMENT '收货日期',
    `handler`        VARCHAR(64)   NULL                    COMMENT '经手人',
    `receiver`       VARCHAR(64)   NULL                    COMMENT '收货员',
    `receive_start_time` DATETIME  NULL                    COMMENT '开始收货时间',
    `status`         TINYINT       NOT NULL DEFAULT 0      COMMENT '单据状态：0-制单保存，1-制单完成（BillStatusEnum）',
    `total_qty`      DECIMAL(18,4) NOT NULL DEFAULT 0      COMMENT '收货数量合计',
    `post_time`      DATETIME      NULL                    COMMENT '过账时间',
    `remark`         VARCHAR(500)  NULL                    COMMENT '备注',
    `create_time`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_user_id` BIGINT        NULL                    COMMENT '创建人（用户ID）',
    `update_user_id` BIGINT        NULL                    COMMENT '更新人（用户ID）',
    `deleted`        TINYINT       NOT NULL DEFAULT 0      COMMENT '逻辑删除标记：0-未删除，1-已删除',
    `version`        INT           NOT NULL DEFAULT 0      COMMENT '乐观锁版本号',
    `cust1`          VARCHAR(255)  NULL                    COMMENT '定制化字段1',
    `cust2`          VARCHAR(255)  NULL                    COMMENT '定制化字段2',
    `cust3`          VARCHAR(255)  NULL                    COMMENT '定制化字段3',
    `cust4`          VARCHAR(255)  NULL                    COMMENT '定制化字段4',
    `cust5`          VARCHAR(255)  NULL                    COMMENT '定制化字段5',
    `cust6`          VARCHAR(255)  NULL                    COMMENT '定制化字段6',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tenant_order_no` (`tenant_id`, `order_no`),
    KEY `idx_tenant_supplier` (`tenant_id`, `supplier_id`),
    KEY `idx_tenant_status` (`tenant_id`, `status`)
) ENGINE = InnoDB COMMENT = '收货单主表';

-- 收货单明细表
CREATE TABLE `receiving_order_item` (
    `id`             BIGINT        NOT NULL                COMMENT '主键（雪花ID）',
    `tenant_id`      BIGINT        NOT NULL                COMMENT '租户ID（真实值，分片键）',
    `org_id`         BIGINT        NOT NULL                COMMENT '机构ID（药店/门店）',
    `order_id`       BIGINT        NOT NULL                COMMENT '收货单ID（关联 receiving_order.id）',
    `seq_no`         INT           NULL                    COMMENT '序号',
    `drug_id`        BIGINT        NULL                    COMMENT '商品ID（关联商品信息）',
    `drug_code`      VARCHAR(64)   NULL                    COMMENT '商品编码',
    `main_barcode`   VARCHAR(64)   NULL                    COMMENT '主条形码',
    `generic_name`   VARCHAR(128)  NULL                    COMMENT '通用名称',
    `drug_name`      VARCHAR(128)  NULL                    COMMENT '商品名称',
    `spec`           VARCHAR(64)   NULL                    COMMENT '规格',
    `unit`           VARCHAR(16)   NULL                    COMMENT '单位',
    `dosage_form`    VARCHAR(32)   NULL                    COMMENT '剂型',
    `origin`         VARCHAR(128)  NULL                    COMMENT '产地',
    `manufacturer`   VARCHAR(128)  NULL                    COMMENT '生产厂家',
    `marketing_holder` VARCHAR(128) NULL                   COMMENT '上市许可持有人',
    `marketing_holder_address` VARCHAR(255) NULL           COMMENT '上市许可持有人地址',
    `approval_no`    VARCHAR(64)   NULL                    COMMENT '批准文号',
    `batch_no`       VARCHAR(64)   NULL                    COMMENT '批号',
    `production_date` DATE         NULL                    COMMENT '生产日期',
    `expiry_date`    DATE          NULL                    COMMENT '有效期',
    `location`       VARCHAR(64)   NULL                    COMMENT '货位',
    `notify_qty`     DECIMAL(18,4) NOT NULL DEFAULT 0      COMMENT '通知数量',
    `receive_qty`    DECIMAL(18,4) NOT NULL DEFAULT 0      COMMENT '收货数量',
    `price`          DECIMAL(18,4) NOT NULL DEFAULT 0      COMMENT '单价',
    `amount`         DECIMAL(18,2) NOT NULL DEFAULT 0      COMMENT '金额',
    `reject_qty`     DECIMAL(18,4) NOT NULL DEFAULT 0      COMMENT '收货拒收数量',
    `reject_amount`  DECIMAL(18,2) NOT NULL DEFAULT 0      COMMENT '收货拒收金额',
    `reject_reason`  VARCHAR(500)  NULL                    COMMENT '拒收原因',
    `receiver`       VARCHAR(64)   NULL                    COMMENT '收货员',
    `receive_time`   DATETIME      NULL                    COMMENT '收货时间',
    `source_type`    VARCHAR(32)   NULL                    COMMENT '源单据类型',
    `source_order_no` VARCHAR(64)  NULL                    COMMENT '原单号',
    `remark`         VARCHAR(500)  NULL                    COMMENT '备注',
    `create_time`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_user_id` BIGINT        NULL                    COMMENT '创建人（用户ID）',
    `update_user_id` BIGINT        NULL                    COMMENT '更新人（用户ID）',
    `deleted`        TINYINT       NOT NULL DEFAULT 0      COMMENT '逻辑删除标记：0-未删除，1-已删除',
    `version`        INT           NOT NULL DEFAULT 0      COMMENT '乐观锁版本号',
    `cust1`          VARCHAR(255)  NULL                    COMMENT '定制化字段1',
    `cust2`          VARCHAR(255)  NULL                    COMMENT '定制化字段2',
    `cust3`          VARCHAR(255)  NULL                    COMMENT '定制化字段3',
    `cust4`          VARCHAR(255)  NULL                    COMMENT '定制化字段4',
    `cust5`          VARCHAR(255)  NULL                    COMMENT '定制化字段5',
    `cust6`          VARCHAR(255)  NULL                    COMMENT '定制化字段6',
    PRIMARY KEY (`id`),
    KEY `idx_order_id` (`order_id`),
    KEY `idx_tenant_drug` (`tenant_id`, `drug_id`)
) ENGINE = InnoDB COMMENT = '收货单明细表';

-- 验收单主表
CREATE TABLE `acceptance_order` (
    `id`             BIGINT        NOT NULL                COMMENT '主键（雪花ID）',
    `tenant_id`      BIGINT        NOT NULL                COMMENT '租户ID（真实值，分片键）',
    `org_id`         BIGINT        NOT NULL                COMMENT '机构ID（药店/门店）',
    `order_no`       VARCHAR(64)   NOT NULL                COMMENT '验收单号',
    `supplier_id`    BIGINT        NOT NULL                COMMENT '供应商ID（关联供应商信息）',
    `supplier_name`  VARCHAR(128)  NULL                    COMMENT '供应商名称',
    `warehouse_id`   BIGINT        NOT NULL                COMMENT '验收仓库ID（关联仓库信息）',
    `warehouse_name` VARCHAR(128)  NULL                    COMMENT '验收仓库名称',
    `source_type`    VARCHAR(32)   NULL                    COMMENT '数据来源',
    `handler`        VARCHAR(64)   NULL                    COMMENT '经手人',
    `source_order_id` BIGINT       NULL                    COMMENT '来源收货单ID（关联 receiving_order.id）',
    `accept_date`    DATE          NULL                    COMMENT '验收日期',
    `accept_user_id` BIGINT        NULL                    COMMENT '验收人ID（员工ID）',
    `accept_time`    DATETIME      NULL                    COMMENT '验收时间',
    `status`         TINYINT       NOT NULL DEFAULT 0      COMMENT '单据状态：0-制单保存，1-制单完成（BillStatusEnum）',
    `total_qty`      DECIMAL(18,4) NOT NULL DEFAULT 0      COMMENT '验收数量合计',
    `post_time`      DATETIME      NULL                    COMMENT '过账时间',
    `remark`         VARCHAR(500)  NULL                    COMMENT '备注',
    `create_time`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_user_id` BIGINT        NULL                    COMMENT '创建人（用户ID）',
    `update_user_id` BIGINT        NULL                    COMMENT '更新人（用户ID）',
    `deleted`        TINYINT       NOT NULL DEFAULT 0      COMMENT '逻辑删除标记：0-未删除，1-已删除',
    `version`        INT           NOT NULL DEFAULT 0      COMMENT '乐观锁版本号',
    `cust1`          VARCHAR(255)  NULL                    COMMENT '定制化字段1',
    `cust2`          VARCHAR(255)  NULL                    COMMENT '定制化字段2',
    `cust3`          VARCHAR(255)  NULL                    COMMENT '定制化字段3',
    `cust4`          VARCHAR(255)  NULL                    COMMENT '定制化字段4',
    `cust5`          VARCHAR(255)  NULL                    COMMENT '定制化字段5',
    `cust6`          VARCHAR(255)  NULL                    COMMENT '定制化字段6',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tenant_order_no` (`tenant_id`, `order_no`),
    KEY `idx_tenant_supplier` (`tenant_id`, `supplier_id`),
    KEY `idx_tenant_status` (`tenant_id`, `status`)
) ENGINE = InnoDB COMMENT = '验收单主表';

-- 验收单明细表
CREATE TABLE `acceptance_order_item` (
    `id`             BIGINT        NOT NULL                COMMENT '主键（雪花ID）',
    `tenant_id`      BIGINT        NOT NULL                COMMENT '租户ID（真实值，分片键）',
    `org_id`         BIGINT        NOT NULL                COMMENT '机构ID（药店/门店）',
    `order_id`       BIGINT        NOT NULL                COMMENT '验收单ID（关联 acceptance_order.id）',
    `seq_no`         INT           NULL                    COMMENT '序号',
    `drug_id`        BIGINT        NULL                    COMMENT '商品ID（关联商品信息）',
    `drug_code`      VARCHAR(64)   NULL                    COMMENT '商品编码',
    `generic_name`   VARCHAR(128)  NULL                    COMMENT '通用名称',
    `drug_name`      VARCHAR(128)  NULL                    COMMENT '商品名称',
    `spec`           VARCHAR(64)   NULL                    COMMENT '规格',
    `unit`           VARCHAR(16)   NULL                    COMMENT '单位',
    `dosage_form`    VARCHAR(32)   NULL                    COMMENT '剂型',
    `origin`         VARCHAR(128)  NULL                    COMMENT '产地',
    `manufacturer`   VARCHAR(128)  NULL                    COMMENT '生产厂家',
    `production_license_no` VARCHAR(64) NULL               COMMENT '生产许可证凭证号',
    `marketing_holder` VARCHAR(128) NULL                   COMMENT '上市持有人',
    `marketing_holder_address` VARCHAR(255) NULL           COMMENT '上市持有人地址',
    `approval_no`    VARCHAR(64)   NULL                    COMMENT '批准文号',
    `batch_no`       VARCHAR(64)   NULL                    COMMENT '批号',
    `production_date` DATE         NULL                    COMMENT '生产日期',
    `expiry_date`    DATE          NULL                    COMMENT '有效期',
    `location`       VARCHAR(64)   NULL                    COMMENT '货位',
    `received_qty`   DECIMAL(18,4) NOT NULL DEFAULT 0      COMMENT '收货数量',
    `accept_qty`     DECIMAL(18,4) NOT NULL DEFAULT 0      COMMENT '验收数量',
    `price`          DECIMAL(18,4) NOT NULL DEFAULT 0      COMMENT '单价',
    `amount`         DECIMAL(18,2) NOT NULL DEFAULT 0      COMMENT '金额',
    `has_inspection_report` TINYINT NULL                   COMMENT '有药检报告：0-否，1-是',
    `supervision_code_recognizable` TINYINT NULL           COMMENT '监管码是否能识别：0-否，1-是',
    `packaging_condition` VARCHAR(64) NULL                 COMMENT '包装情况',
    `appearance_quality` VARCHAR(64) NULL                  COMMENT '外观质量',
    `acceptance_status` VARCHAR(32) NULL                   COMMENT '验收状态',
    `accept_time`    DATETIME      NULL                    COMMENT '验收时间',
    `sample_qty`     DECIMAL(18,4) NOT NULL DEFAULT 0      COMMENT '抽样数量',
    `reject_qty`     DECIMAL(18,4) NOT NULL DEFAULT 0      COMMENT '拒收数量',
    `reject_reason`  VARCHAR(500)  NULL                    COMMENT '拒收原因',
    `reject_days`    INT           NULL                    COMMENT '拒收天数',
    `unqualified_qty` DECIMAL(18,4) NOT NULL DEFAULT 0     COMMENT '不合格数量',
    `unqualified_reason` VARCHAR(500) NULL                 COMMENT '不合格原因',
    `handle_type`    TINYINT       NULL                    COMMENT '不合格处理方式：1-退货，2-换货，3-让步接收（UnqualifiedHandleEnum）',
    `pending_qty`    DECIMAL(18,4) NOT NULL DEFAULT 0      COMMENT '待处理数量',
    `receiver`       VARCHAR(64)   NULL                    COMMENT '收货员',
    `remark`         VARCHAR(500)  NULL                    COMMENT '备注',
    `create_time`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_user_id` BIGINT        NULL                    COMMENT '创建人（用户ID）',
    `update_user_id` BIGINT        NULL                    COMMENT '更新人（用户ID）',
    `deleted`        TINYINT       NOT NULL DEFAULT 0      COMMENT '逻辑删除标记：0-未删除，1-已删除',
    `version`        INT           NOT NULL DEFAULT 0      COMMENT '乐观锁版本号',
    `cust1`          VARCHAR(255)  NULL                    COMMENT '定制化字段1',
    `cust2`          VARCHAR(255)  NULL                    COMMENT '定制化字段2',
    `cust3`          VARCHAR(255)  NULL                    COMMENT '定制化字段3',
    `cust4`          VARCHAR(255)  NULL                    COMMENT '定制化字段4',
    `cust5`          VARCHAR(255)  NULL                    COMMENT '定制化字段5',
    `cust6`          VARCHAR(255)  NULL                    COMMENT '定制化字段6',
    PRIMARY KEY (`id`),
    KEY `idx_order_id` (`order_id`),
    KEY `idx_tenant_drug` (`tenant_id`, `drug_id`)
) ENGINE = InnoDB COMMENT = '验收单明细表';

-- 采购入库单主表
CREATE TABLE `purchase_inbound_order` (
    `id`             BIGINT        NOT NULL                COMMENT '主键（雪花ID）',
    `tenant_id`      BIGINT        NOT NULL                COMMENT '租户ID（真实值，分片键）',
    `org_id`         BIGINT        NOT NULL                COMMENT '机构ID（药店/门店）',
    `order_no`       VARCHAR(64)   NOT NULL                COMMENT '入库单号',
    `supplier_id`    BIGINT        NOT NULL                COMMENT '供应商ID（关联供应商信息）',
    `supplier_name`  VARCHAR(128)  NULL                    COMMENT '供应商名称',
    `warehouse_id`   BIGINT        NOT NULL                COMMENT '入库仓库ID（关联仓库信息）',
    `warehouse_name` VARCHAR(128)  NULL                    COMMENT '入库仓库名称',
    `invoice_type`   VARCHAR(32)   NULL                    COMMENT '发票类型',
    `invoice_no`     VARCHAR(64)   NULL                    COMMENT '发票号码',
    `handler`        VARCHAR(64)   NULL                    COMMENT '经手人',
    `supplier_salesman` VARCHAR(64) NULL                   COMMENT '供应商业务员',
    `payment_method` VARCHAR(32)   NULL                    COMMENT '付款方式',
    `settlement_method` VARCHAR(32) NULL                   COMMENT '结算方式',
    `pre_settlement_date` DATE      NULL                   COMMENT '预结算日期',
    `arrival_no`     VARCHAR(64)   NULL                    COMMENT '来货单号',
    `acceptor`       VARCHAR(64)   NULL                    COMMENT '验收人',
    `source_order_id` BIGINT       NULL                    COMMENT '来源验收单ID（关联 acceptance_order.id）',
    `inbound_date`   DATE          NULL                    COMMENT '入库日期',
    `status`         TINYINT       NOT NULL DEFAULT 0      COMMENT '单据状态：0-制单保存，1-制单完成（BillStatusEnum）',
    `total_qty`      DECIMAL(18,4) NOT NULL DEFAULT 0      COMMENT '入库数量合计',
    `total_amount`   DECIMAL(18,2) NOT NULL DEFAULT 0      COMMENT '入库金额合计',
    `post_time`      DATETIME      NULL                    COMMENT '过账时间',
    `remark`         VARCHAR(500)  NULL                    COMMENT '备注',
    `create_time`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_user_id` BIGINT        NULL                    COMMENT '创建人（用户ID）',
    `update_user_id` BIGINT        NULL                    COMMENT '更新人（用户ID）',
    `deleted`        TINYINT       NOT NULL DEFAULT 0      COMMENT '逻辑删除标记：0-未删除，1-已删除',
    `version`        INT           NOT NULL DEFAULT 0      COMMENT '乐观锁版本号',
    `cust1`          VARCHAR(255)  NULL                    COMMENT '定制化字段1',
    `cust2`          VARCHAR(255)  NULL                    COMMENT '定制化字段2',
    `cust3`          VARCHAR(255)  NULL                    COMMENT '定制化字段3',
    `cust4`          VARCHAR(255)  NULL                    COMMENT '定制化字段4',
    `cust5`          VARCHAR(255)  NULL                    COMMENT '定制化字段5',
    `cust6`          VARCHAR(255)  NULL                    COMMENT '定制化字段6',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tenant_order_no` (`tenant_id`, `order_no`),
    KEY `idx_tenant_supplier` (`tenant_id`, `supplier_id`),
    KEY `idx_tenant_status` (`tenant_id`, `status`)
) ENGINE = InnoDB COMMENT = '采购入库单主表';

-- 采购入库单明细表
CREATE TABLE `purchase_inbound_order_item` (
    `id`             BIGINT        NOT NULL                COMMENT '主键（雪花ID）',
    `tenant_id`      BIGINT        NOT NULL                COMMENT '租户ID（真实值，分片键）',
    `org_id`         BIGINT        NOT NULL                COMMENT '机构ID（药店/门店）',
    `order_id`       BIGINT        NOT NULL                COMMENT '入库单ID（关联 purchase_inbound_order.id）',
    `seq_no`         INT           NULL                    COMMENT '序号',
    `drug_id`        BIGINT        NULL                    COMMENT '商品ID（关联商品信息）',
    `drug_code`      VARCHAR(64)   NULL                    COMMENT '商品编码',
    `generic_name`   VARCHAR(128)  NULL                    COMMENT '通用名称',
    `drug_name`      VARCHAR(128)  NULL                    COMMENT '商品名称',
    `spec`           VARCHAR(64)   NULL                    COMMENT '规格',
    `unit`           VARCHAR(16)   NULL                    COMMENT '单位',
    `dosage_form`    VARCHAR(32)   NULL                    COMMENT '剂型',
    `origin`         VARCHAR(128)  NULL                    COMMENT '产地',
    `manufacturer`   VARCHAR(128)  NULL                    COMMENT '生产厂家',
    `production_license_no` VARCHAR(64) NULL               COMMENT '生产许可证凭证号',
    `marketing_holder` VARCHAR(128) NULL                   COMMENT '上市持有人',
    `marketing_holder_address` VARCHAR(255) NULL           COMMENT '上市持有人地址',
    `approval_no`    VARCHAR(64)   NULL                    COMMENT '批准文号',
    `batch_no`       VARCHAR(64)   NULL                    COMMENT '批号',
    `production_date` DATE         NULL                    COMMENT '生产日期',
    `expiry_date`    DATE          NULL                    COMMENT '有效期',
    `inbound_qty`    DECIMAL(18,4) NOT NULL DEFAULT 0      COMMENT '入库数量',
    `price`          DECIMAL(18,4) NOT NULL DEFAULT 0      COMMENT '单价',
    `amount`         DECIMAL(18,2) NOT NULL DEFAULT 0      COMMENT '金额',
    `retail_price`   DECIMAL(18,4) NULL                    COMMENT '零售价',
    `member_price`   DECIMAL(18,4) NULL                    COMMENT '会员价',
    `remark`         VARCHAR(500)  NULL                    COMMENT '备注',
    `create_time`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_user_id` BIGINT        NULL                    COMMENT '创建人（用户ID）',
    `update_user_id` BIGINT        NULL                    COMMENT '更新人（用户ID）',
    `deleted`        TINYINT       NOT NULL DEFAULT 0      COMMENT '逻辑删除标记：0-未删除，1-已删除',
    `version`        INT           NOT NULL DEFAULT 0      COMMENT '乐观锁版本号',
    `cust1`          VARCHAR(255)  NULL                    COMMENT '定制化字段1',
    `cust2`          VARCHAR(255)  NULL                    COMMENT '定制化字段2',
    `cust3`          VARCHAR(255)  NULL                    COMMENT '定制化字段3',
    `cust4`          VARCHAR(255)  NULL                    COMMENT '定制化字段4',
    `cust5`          VARCHAR(255)  NULL                    COMMENT '定制化字段5',
    `cust6`          VARCHAR(255)  NULL                    COMMENT '定制化字段6',
    PRIMARY KEY (`id`),
    KEY `idx_order_id` (`order_id`),
    KEY `idx_tenant_drug` (`tenant_id`, `drug_id`)
) ENGINE = InnoDB COMMENT = '采购入库单明细表';

-- 拒收单主表
CREATE TABLE `rejection_order` (
    `id`             BIGINT        NOT NULL                COMMENT '主键（雪花ID）',
    `tenant_id`      BIGINT        NOT NULL                COMMENT '租户ID（真实值，分片键）',
    `org_id`         BIGINT        NOT NULL                COMMENT '机构ID（药店/门店）',
    `order_no`       VARCHAR(64)   NOT NULL                COMMENT '拒收单号',
    `reject_date`    DATE          NULL                    COMMENT '单据日期',
    `warehouse_id`   BIGINT        NULL                    COMMENT '仓库ID（关联仓库信息）',
    `warehouse_name` VARCHAR(128)  NULL                    COMMENT '仓库名称',
    `source_type`    VARCHAR(32)   NULL                    COMMENT '数据来源',
    `supplier_id`    BIGINT        NULL                    COMMENT '往来单位ID',
    `supplier_name`  VARCHAR(128)  NULL                    COMMENT '往来单位名称',
    `arrival_no`     VARCHAR(64)   NULL                    COMMENT '来货单号',
    `handler`        VARCHAR(64)   NULL                    COMMENT '经手人',
    `receiver`       VARCHAR(64)   NULL                    COMMENT '收货员',
    `status`         TINYINT       NOT NULL DEFAULT 0      COMMENT '单据状态：0-制单保存，1-制单完成（BillStatusEnum）',
    `post_time`      DATETIME      NULL                    COMMENT '过账时间',
    `remark`         VARCHAR(500)  NULL                    COMMENT '备注',
    `create_time`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_user_id` BIGINT        NULL                    COMMENT '创建人（用户ID）',
    `update_user_id` BIGINT        NULL                    COMMENT '更新人（用户ID）',
    `deleted`        TINYINT       NOT NULL DEFAULT 0      COMMENT '逻辑删除标记：0-未删除，1-已删除',
    `version`        INT           NOT NULL DEFAULT 0      COMMENT '乐观锁版本号',
    `cust1`          VARCHAR(255)  NULL                    COMMENT '定制化字段1',
    `cust2`          VARCHAR(255)  NULL                    COMMENT '定制化字段2',
    `cust3`          VARCHAR(255)  NULL                    COMMENT '定制化字段3',
    `cust4`          VARCHAR(255)  NULL                    COMMENT '定制化字段4',
    `cust5`          VARCHAR(255)  NULL                    COMMENT '定制化字段5',
    `cust6`          VARCHAR(255)  NULL                    COMMENT '定制化字段6',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tenant_order_no` (`tenant_id`, `order_no`),
    KEY `idx_tenant_supplier` (`tenant_id`, `supplier_id`),
    KEY `idx_tenant_status` (`tenant_id`, `status`)
) ENGINE = InnoDB COMMENT = '拒收单主表';

-- 拒收单明细表
CREATE TABLE `rejection_order_item` (
    `id`             BIGINT        NOT NULL                COMMENT '主键（雪花ID）',
    `tenant_id`      BIGINT        NOT NULL                COMMENT '租户ID（真实值，分片键）',
    `org_id`         BIGINT        NOT NULL                COMMENT '机构ID（药店/门店）',
    `order_id`       BIGINT        NOT NULL                COMMENT '拒收单ID（关联 rejection_order.id）',
    `seq_no`         INT           NULL                    COMMENT '序号',
    `drug_id`        BIGINT        NULL                    COMMENT '商品ID（关联商品信息）',
    `drug_code`      VARCHAR(64)   NULL                    COMMENT '商品编码',
    `drug_name`      VARCHAR(128)  NULL                    COMMENT '商品名称',
    `unit`           VARCHAR(16)   NULL                    COMMENT '单位',
    `spec`           VARCHAR(64)   NULL                    COMMENT '规格',
    `dosage_form`    VARCHAR(32)   NULL                    COMMENT '剂型',
    `origin`         VARCHAR(128)  NULL                    COMMENT '产地',
    `batch_no`       VARCHAR(64)   NULL                    COMMENT '批号',
    `production_date` DATE         NULL                    COMMENT '生产日期',
    `expiry_date`    DATE          NULL                    COMMENT '有效期',
    `reject_qty`     DECIMAL(18,4) NOT NULL DEFAULT 0      COMMENT '拒收数量',
    `reject_reason`  VARCHAR(500)  NULL                    COMMENT '拒收原因',
    `remark`         VARCHAR(500)  NULL                    COMMENT '备注',
    `create_time`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_user_id` BIGINT        NULL                    COMMENT '创建人（用户ID）',
    `update_user_id` BIGINT        NULL                    COMMENT '更新人（用户ID）',
    `deleted`        TINYINT       NOT NULL DEFAULT 0      COMMENT '逻辑删除标记：0-未删除，1-已删除',
    `version`        INT           NOT NULL DEFAULT 0      COMMENT '乐观锁版本号',
    `cust1`          VARCHAR(255)  NULL                    COMMENT '定制化字段1',
    `cust2`          VARCHAR(255)  NULL                    COMMENT '定制化字段2',
    `cust3`          VARCHAR(255)  NULL                    COMMENT '定制化字段3',
    `cust4`          VARCHAR(255)  NULL                    COMMENT '定制化字段4',
    `cust5`          VARCHAR(255)  NULL                    COMMENT '定制化字段5',
    `cust6`          VARCHAR(255)  NULL                    COMMENT '定制化字段6',
    PRIMARY KEY (`id`),
    KEY `idx_order_id` (`order_id`),
    KEY `idx_tenant_drug` (`tenant_id`, `drug_id`)
) ENGINE = InnoDB COMMENT = '拒收单明细表';

-- =====================================================================
-- adrug_bus_pms_1（结构与 _0 完全一致）
-- =====================================================================
USE `adrug_bus_pms_1`;

CREATE TABLE `purchase_order` LIKE `adrug_bus_pms_0`.`purchase_order`;
CREATE TABLE `purchase_order_item` LIKE `adrug_bus_pms_0`.`purchase_order_item`;
CREATE TABLE `receiving_order` LIKE `adrug_bus_pms_0`.`receiving_order`;
CREATE TABLE `receiving_order_item` LIKE `adrug_bus_pms_0`.`receiving_order_item`;
CREATE TABLE `acceptance_order` LIKE `adrug_bus_pms_0`.`acceptance_order`;
CREATE TABLE `acceptance_order_item` LIKE `adrug_bus_pms_0`.`acceptance_order_item`;
CREATE TABLE `purchase_inbound_order` LIKE `adrug_bus_pms_0`.`purchase_inbound_order`;
CREATE TABLE `purchase_inbound_order_item` LIKE `adrug_bus_pms_0`.`purchase_inbound_order_item`;
CREATE TABLE `rejection_order` LIKE `adrug_bus_pms_0`.`rejection_order`;
CREATE TABLE `rejection_order_item` LIKE `adrug_bus_pms_0`.`rejection_order_item`;
